## Copyright (c) 2026 AccelByte Inc. All Rights Reserved.
## This is licensed software from AccelByte Inc, for limitations
## and restrictions contact your company contract manager.
## =============================================================================
## lobby_ws_message_types.gd
## Auto-generated from lobby.schema.yaml — DO NOT EDIT
## Service: justice-lobby-ws-service
## Version: 3.35.2
## =============================================================================
##
## Message type string constants for AccelByte Lobby WebSocket protocol.
##
## Usage:
##   LobbyWsMessageTypes.ACCEPT_FRIENDS_REQUEST  # "acceptFriendsRequest"
##   LobbyWsMessageTypes.PARTY_INVITE_NOTIF      # "partyInviteNotif"
## =============================================================================

class_name LobbyWsMessageTypes
extends RefCounted

const ACCEPT_FRIENDS_NOTIF = "acceptFriendsNotif"
const ACCEPT_FRIENDS_REQUEST = "acceptFriendsRequest"
const ACCEPT_FRIENDS_RESPONSE = "acceptFriendsResponse"
const BLOCK_PLAYER_NOTIF = "blockPlayerNotif"
const BLOCK_PLAYER_REQUEST = "blockPlayerRequest"
const BLOCK_PLAYER_RESPONSE = "blockPlayerResponse"
const CANCEL_FRIENDS_NOTIF = "cancelFriendsNotif"
const CANCEL_FRIENDS_REQUEST = "cancelFriendsRequest"
const CANCEL_FRIENDS_RESPONSE = "cancelFriendsResponse"
const CANCEL_MATCHMAKING_REQUEST = "cancelMatchmakingRequest"
const CANCEL_MATCHMAKING_RESPONSE = "cancelMatchmakingResponse"
const CHANNEL_CHAT_NOTIF = "channelChatNotif"
const CLIENT_RESET_REQUEST = "clientResetRequest"
const CONNECT_NOTIF = "connectNotif"
const DISCONNECT_NOTIF = "disconnectNotif"
const DS_NOTIF = "dsNotif"
const ERROR_NOTIF = "errorNotif"
const EXIT_ALL_CHANNEL = "exitAllChannel"
const FRIENDS_STATUS_REQUEST = "friendsStatusRequest"
const FRIENDS_STATUS_RESPONSE = "friendsStatusResponse"
const GET_ALL_SESSION_ATTRIBUTE_REQUEST = "getAllSessionAttributeRequest"
const GET_ALL_SESSION_ATTRIBUTE_RESPONSE = "getAllSessionAttributeResponse"
const GET_FRIENDSHIP_STATUS_REQUEST = "getFriendshipStatusRequest"
const GET_FRIENDSHIP_STATUS_RESPONSE = "getFriendshipStatusResponse"
const GET_SESSION_ATTRIBUTE_REQUEST = "getSessionAttributeRequest"
const GET_SESSION_ATTRIBUTE_RESPONSE = "getSessionAttributeResponse"
const HEARTBEAT = "heartbeat"
const JOIN_DEFAULT_CHANNEL_REQUEST = "joinDefaultChannelRequest"
const JOIN_DEFAULT_CHANNEL_RESPONSE = "joinDefaultChannelResponse"
const LIST_INCOMING_FRIENDS_REQUEST = "listIncomingFriendsRequest"
const LIST_INCOMING_FRIENDS_RESPONSE = "listIncomingFriendsResponse"
const LIST_OF_FRIENDS_REQUEST = "listOfFriendsRequest"
const LIST_OF_FRIENDS_RESPONSE = "listOfFriendsResponse"
const LIST_ONLINE_FRIENDS_REQUEST = "listOnlineFriendsRequest"
const LIST_OUTGOING_FRIENDS_REQUEST = "listOutgoingFriendsRequest"
const LIST_OUTGOING_FRIENDS_RESPONSE = "listOutgoingFriendsResponse"
const MATCHMAKING_NOTIF = "matchmakingNotif"
const MESSAGE_NOTIF = "messageNotif"
const MESSAGE_SESSION_NOTIF = "messageSessionNotif"
const OFFLINE_NOTIFICATION_REQUEST = "offlineNotificationRequest"
const OFFLINE_NOTIFICATION_RESPONSE = "offlineNotificationResponse"
const ONLINE_FRIENDS = "onlineFriends"
const PARTY_CHAT_NOTIF = "partyChatNotif"
const PARTY_CHAT_REQUEST = "partyChatRequest"
const PARTY_CHAT_RESPONSE = "partyChatResponse"
const PARTY_CREATE_REQUEST = "partyCreateRequest"
const PARTY_CREATE_RESPONSE = "partyCreateResponse"
const PARTY_DATA_UPDATE_NOTIF = "partyDataUpdateNotif"
const PARTY_GET_INVITED_NOTIF = "partyGetInvitedNotif"
const PARTY_INFO_REQUEST = "partyInfoRequest"
const PARTY_INFO_RESPONSE = "partyInfoResponse"
const PARTY_INVITE_NOTIF = "partyInviteNotif"
const PARTY_INVITE_REQUEST = "partyInviteRequest"
const PARTY_INVITE_RESPONSE = "partyInviteResponse"
const PARTY_JOIN_NOTIF = "partyJoinNotif"
const PARTY_JOIN_REQUEST = "partyJoinRequest"
const PARTY_JOIN_RESPONSE = "partyJoinResponse"
const PARTY_KICK_NOTIF = "partyKickNotif"
const PARTY_KICK_REQUEST = "partyKickRequest"
const PARTY_KICK_RESPONSE = "partyKickResponse"
const PARTY_LEAVE_NOTIF = "partyLeaveNotif"
const PARTY_LEAVE_REQUEST = "partyLeaveRequest"
const PARTY_LEAVE_RESPONSE = "partyLeaveResponse"
const PARTY_PROMOTE_LEADER_REQUEST = "partyPromoteLeaderRequest"
const PARTY_PROMOTE_LEADER_RESPONSE = "partyPromoteLeaderResponse"
const PARTY_REJECT_NOTIF = "partyRejectNotif"
const PARTY_REJECT_REQUEST = "partyRejectRequest"
const PARTY_REJECT_RESPONSE = "partyRejectResponse"
const PERSONAL_CHAT_HISTORY_REQUEST = "personalChatHistoryRequest"
const PERSONAL_CHAT_HISTORY_RESPONSE = "personalChatHistoryResponse"
const PERSONAL_CHAT_NOTIF = "personalChatNotif"
const PERSONAL_CHAT_REQUEST = "personalChatRequest"
const PERSONAL_CHAT_RESPONSE = "personalChatResponse"
const REFRESH_TOKEN_REQUEST = "refreshTokenRequest"
const REFRESH_TOKEN_RESPONSE = "refreshTokenResponse"
const REJECT_FRIENDS_NOTIF = "rejectFriendsNotif"
const REJECT_FRIENDS_REQUEST = "rejectFriendsRequest"
const REJECT_FRIENDS_RESPONSE = "rejectFriendsResponse"
const REMATCHMAKING_NOTIF = "rematchmakingNotif"
const REQUEST_FRIENDS_NOTIF = "requestFriendsNotif"
const REQUEST_FRIENDS_REQUEST = "requestFriendsRequest"
const REQUEST_FRIENDS_RESPONSE = "requestFriendsResponse"
const SEND_CHANNEL_CHAT_REQUEST = "sendChannelChatRequest"
const SEND_CHANNEL_CHAT_RESPONSE = "sendChannelChatResponse"
const SET_READY_CONSENT_NOTIF = "setReadyConsentNotif"
const SET_READY_CONSENT_REQUEST = "setReadyConsentRequest"
const SET_READY_CONSENT_RESPONSE = "setReadyConsentResponse"
const SET_SESSION_ATTRIBUTE_REQUEST = "setSessionAttributeRequest"
const SET_SESSION_ATTRIBUTE_RESPONSE = "setSessionAttributeResponse"
const SET_USER_STATUS_REQUEST = "setUserStatusRequest"
const SET_USER_STATUS_RESPONSE = "setUserStatusResponse"
const SHUTDOWN_NOTIF = "shutdownNotif"
const SIGNALING_P2P_NOTIF = "signalingP2PNotif"
const START_MATCHMAKING_REQUEST = "startMatchmakingRequest"
const START_MATCHMAKING_RESPONSE = "startMatchmakingResponse"
const UNBLOCK_PLAYER_NOTIF = "unblockPlayerNotif"
const UNBLOCK_PLAYER_REQUEST = "unblockPlayerRequest"
const UNBLOCK_PLAYER_RESPONSE = "unblockPlayerResponse"
const UNFRIEND_NOTIF = "unfriendNotif"
const UNFRIEND_REQUEST = "unfriendRequest"
const UNFRIEND_RESPONSE = "unfriendResponse"
const USER_BANNED_NOTIFICATION = "userBannedNotification"
const USER_METRIC_REQUEST = "userMetricRequest"
const USER_METRIC_RESPONSE = "userMetricResponse"
const USER_STATUS_NOTIF = "userStatusNotif"
